# Generated by Django 4.2.6 on 2023-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('email', models.EmailField(max_length=32, verbose_name='Email')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone')),
                ('password', models.CharField(max_length=32, verbose_name='Password')),
            ],
        ),
    ]
