"""
Django settings for s25 project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
    'web',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'web.middlewares.xFrame.XFrameOptionsMiddleware',
    'web.middlewares.auth.AuthMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 's25.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 's25.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#export REDIS_URL='redis://127.0.0.1:6379/1'
#export REDIS_PASSWORD='Archeruz72!'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDIS_URL'),
        "OPTIONS":{
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 1000},
            "PASSWORD": os.getenv('REDIS_PASSWORD'),
        },
    }
        
}

#https://testdriven.io/blog/storing-django-static-and-media-files-on-amazon-s3/

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = 'ca-central-1'
AWS_S3_FILE_OVERWRITE = False
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_DEFAULT_ACL = None  # or use None to inherit bucket's ACL
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_LOCATION = 'static'
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/' #https://[your-bucket-name].s3.amazonaws.com/static/
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_LOCATION = 'media'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'
#AWS_QUERYSTRING_AUTH = True
#AWS_EXPIRY = 60 * 60 * 24 * 7  # 1 week

#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'web/static'),
    # other folders containing static files if any
]

MEDIA_URL = '/mediafiles/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Sid": "PublicReadForStaticFiles",
#             "Effect": "Allow",
#             "Principal": "*",
#             "Action": ["s3:GetObject"],
#             "Resource": ["arn:aws:s3:::YOUR_BUCKET_NAME/static/*"]
#         }
#     ]
# }

CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", 
                 "https://cdn.bootcdn.net",
                 "https://cdnjs.cloudflare.com",  # FontAwesome and other styles
                 "https://taskwiki.s3.amazonaws.com",
                 "'unsafe-inline'")  # Use 'unsafe-inline' cautiously
CSP_SCRIPT_SRC = ("'self'", 
                  "https://code.jquery.com",
                  "https://cdn.bootcdn.net",
                  "https://taskwiki.s3.amazonaws.com",
                  "'unsafe-inline'")  # Use 'unsafe-inline' cautiously
CSP_IMG_SRC = ("'self'", 'data:', 'https://taskwiki.s3.amazonaws.com',
               "https://taskwiki.s3.ca-central-1.amazonaws.com",)
CSP_FONT_SRC = ("'self'",
                "https://cdnjs.cloudflare.com",  # Allow fonts from FontAwesome
                "https://taskwiki.s3.amazonaws.com",
                "https://taskwiki.s3.ca-central-1.amazonaws.com",
                "https://cdn.bootcdn.net",  # Allow fonts from FontAwesome
                "data:")  # Allow data URI for fonts

WHITE_REGEX_LIST = [
    '/register/',
    '/login/',
    '/login/sms/',
    '/image/code/',
    '/send/sms/',
    '/logout/',
    '/index/',
]